//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by vc6.rc
//
#define IDD_VC6_DIALOG                  102
#define IDD_menu_DIALOG                 102
#define IDD_MENU_DIALOG                 102
#define IDD_MUNU                        102
#define IDD_REGISTER                    224
#define IDD_HEROS                       225
#define IDD_GAME                        226
#define IDD_HELP                        227
#define IDD_DIALOG_CTRL                 279
#define IDR_MAINFRAME                   281
#define IDI_EVER                        283
#define IDD_STUDIO                      284
#define IDD_REGISTER_LOGIN              286
#define IDD_REGISTER_REG                287
#define IDD_REGISTER_MODIFY             288
#define IDD_REGISTER_RECHARGE           289
#define IDD_DIALOG_FOREVER              290
#define IDD_REGISTER_LOGIN_EVER         291
#define IDD_REGISTER_MODIFY_EVER        292
#define IDD_REGISTER_RECHARGE_EVER      293
#define IDD_REGISTER_REG_EVER           294
#define IDC_STORE                       1000
#define IDC_RESTORE                     1001
#define IDC_                            1005
#define IDC_kent                        1005
#define IDC_KENT_TAB                    1006
#define IDC_RADIO1                      1011
#define IDC_EDIT_HERO_SELECT1           1014
#define IDC_EDIT_HERO_SELECT2           1015
#define IDC_EDIT_HERO_SELECT3           1016
#define IDC_EDIT_HERO_SELECT_EVER2      1017
#define IDC_EDIT_HERO_SELECT_EVER3      1018
#define IDC_COMBOIDC_HERO_SELECT1       1020
#define IDC_COMBOIDC_HERO_SELECT2       1021
#define IDC_COMBO3                      1022
#define IDC_COMBOIDC_HERO_SELECT3       1022
#define IDC_HERO_RND                    1025
#define IDC_HERO_ALLRND                 1026
#define IDC_COMBOIDC_OCCUPY_MODE        1027
#define IDC_CHECK3                      1028
#define IDC_CHECK4                      1029
#define IDC_EDIT_DIE_CALL               1030
#define IDC_COMBOIDC_DIE_CALL_PRO       1031
#define IDC_COMBOIDC_DIE_CALL_CHANCE    1031
#define IDC_COMBOIDC_MATCH_MODE         1032
#define IDC_HERO_ALLRND2                1032
#define IDC_HERO_RUIZI                  1032
#define IDC_CHECK_FINISH                1033
#define IDC_HERO_RUIZI_EVER             1033
#define IDC_CHECK_RECONNECT             1034
#define IDC_CHECK_FAST_CONNECT          1035
#define IDC_BUTTON1                     1036
#define IDC_BUTTON2                     1037
#define IDC_EDIT1                       1037
#define IDC_BUTTON3                     1038
#define IDC_BUTTON4                     1039
#define IDC_COMBOIDC_HACK_MODE          1040
#define IDC_COMBOIDC_BIND_MODE          1041
#define IDC_BUTTON_MENU                 1042
#define IDC_CHECK_RECONNECT2            1042
#define IDC_BUTTON_START                1043
#define IDC_CHECK_SHUTDOWN              1043
#define IDC_BUTTON_STOP                 1044
#define IDC_CHECK_SHUTDOWN2             1044
#define IDC_CHECK_NEXTSTOP              1044
#define IDC_CHECK_NEXTSHUTDOWN          1045
#define IDC_BUTTON_HELP                 1046
#define IDC_EDIT_QQ_KEY                 1047
#define IDC_BUTTON_REG                  1048
#define IDC_COMBO_QQ_AREA               1048
#define IDC_BUTTON_TRY                  1049
#define IDC_EDIT_IP                     1049
#define IDC_BUTTON_BIND                 1050
#define IDC_EDIT_QQ_IP                  1050
#define IDC_EDIT_QQ_GROWIP              1050
#define IDC_EDIT3                       1051
#define IDC_EDIT_QQ_IP2                 1052
#define IDC_EDIT_QQ_NAME                1052
#define IDC_EDIT_PORT                   1053
#define IDC_EDIT_QQ_STOPIP              1054
#define IDC_COMBO_QU_STUDIO             1055
#define IDC_EDIT_QQ_STOPIP2             1055
#define IDC_EDIT_QQ_STOPSTAGE           1055
#define IDC_BUTTON_REG_STUDIO           1056
#define IDC_EDIT_CHANGE_TIME            1056
#define IDC_BUTTON_BUY                  1057
#define IDC_BUTTON_BIND_STUDIO          1057
#define IDC_EDIT_CHANGE_TIME2           1057
#define IDC_EDIT_CHANGE_TASK_NUM        1057
#define IDC_BUTTON_BUY2                 1058
#define IDC_COMBO_IDENTIFY              1059
#define IDC_BUTTON_REG_IDENTIFY         1060
#define IDC_COMBO_KSS_CHOOSE            1061
#define IDC_BUTTON_KSS_COMMAND          1062
#define IDC_DATAGRID1                   1064
#define IDC_DATAGRID_QQ                 1064
#define IDC_LIST_QQ                     1069
#define IDC_BUTTON_ADD                  1070
#define IDC_BUTTON_RECHARGE             1070
#define IDC_BUTTON_DELETE               1071
#define IDC_BUTTON_NAME_MANAGE          1072
#define IDC_EDIT_QQ_NUM                 1073
#define IDC_CHECK1                      1074
#define IDC_CHECK_enable_studio         1074
#define IDC_EDIT_TASK_ID                1074
#define IDC_BUTTON_TRY_STUDIO           1075
#define IDC_EDIT_REG_STUDIO             1076
#define IDC_EDIT_IDENTIFY_CODE          1077
#define IDC_EDIT_IDENTIFY_CODE_SYDT     1077
#define IDC_STATIC_CONNECT_STATE        1078
#define IDC_EDIT_IDENTIFY_DAMA2_USER    1080
#define IDC_EDIT_IDENTIFY_DAMA2_KEY     1081
#define IDC_STATIC_DAMA2_USER           1083
#define IDC_STATIC_DAMA2_KEY            1084
#define IDC_EDIT_IDENTIFY_UUWISE_USER   1085
#define IDC_EDIT_IDENTIFY_DAMA2_KEY2    1086
#define IDC_EDIT_IDENTIFY_UUWISE_KEY    1086
#define IDC_STATIC_UUWISE_USER          1087
#define IDC_STATIC_UUWISE_KEY           1088
#define IDC_EDIT_KSS_USER               1089
#define IDC_STATIC_USER                 1090
#define IDC_STATIC_KEY                  1091
#define IDC_STATIC_KSS_KEY_TEXT         1091
#define IDC_EDIT_KSS_KEY                1092
#define IDC_STATIC_KSS_CDKEY            1093
#define IDC_STATIC_KSS_CDKEY_TEXT       1093
#define IDC_EDIT_IDENTIFY_DAMA2_KEY5    1094
#define IDC_TAB_REG                     1094
#define IDC_EDIT_MODIFY_USER            1095
#define IDC_EDIT_MODIFY_SUPER_KEY       1096
#define IDC_EDIT_MODIFY_LOGIN_KEY       1097
#define IDC_BUTTON_MODIFY               1098
#define IDC_EDIT_REG_CDKEY              1098
#define IDC_EDIT_REG_USER               1099
#define IDC_EDIT_REG_SUPER_KEY          1100
#define IDC_EDIT_REG_LOGIN_KEY          1101
#define IDC_EDIT_RECHARGE_CDKEY         1102
#define IDC_EDIT_RECHARGE_USER          1103
#define IDC_EDIT_LOGIN_USER             1104
#define IDC_EDIT_LOGIN_KEY              1105
#define IDC_STATIC_LOGIN_NOTICE         1106
#define IDC_STATIC_MODIFY_NOTICE        1107
#define IDC_STATIC_RECHARGE_NOTICE      1108
#define IDC_STATIC_REG_NOTICE           1109
#define IDC_BUTTON_LOGIN                1110
#define IDC_BUTTON_LOGIN2               1111
#define IDC_EDIT_SHUTDOWN               1111
#define IDC_EDIT_SHUTDOWN_HOUR          1111
#define IDC_COMBO1                      1112
#define IDC_CHECK_FINSIH_ENABLE         1113
#define IDC_STATIC_INIT_IP              1114
#define IDC_STATIC_NOW_STAGE            1114
#define IDC_STATIC_NOW_IP               1115
#define IDC_EDIT_HERO_SELECT_EVER1      1115
#define IDC_HERO_RND_EVER               1116
#define IDC_STATIC_NOW_STAGE2           1116
#define IDC_COMBOIDC_MATCH_MODE_EVER    1117
#define IDC_CHECK_FINSIH_ENABLE2        1117
#define IDC_CHECK_FORCE_DOWNCPU         1117
#define IDC_CHECK_CHANGE_TASK           1118
#define IDC_CHECK_RECONNECT_EVER        1119
#define IDC_COMBO_QQ_AREA_EVER          1120
#define IDC_CHECK_FINSIH_ENABLE3        1120
#define IDC_CHECK_AUTORUN               1120
#define IDC_EDIT_QQ_KEY_EVER            1121
#define IDC_EDIT_QQ_NUM_EVER            1122
#define IDC_COMBO_                      1123
#define IDC_COMBO_RESOLUTION            1123
#define IDC_BUTTON_STORE_EVER           1124
#define IDC_BUTTON_CANCEL_EVER          1125
#define IDC_STATIC_AREA                 1126

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        293
#define _APS_NEXT_COMMAND_VALUE         32772
#define _APS_NEXT_CONTROL_VALUE         1127
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
